### ISSUE TITLE
Feature request: Reverse wheel scroll option

### ISSUE THREAD

**Issue by hufftheweevil** [89pleasure/cities2-extended-hotkeys#3]
Awesome mod!
Only thing I wish was different was for the scroll wheel to be reversed for changing the elevation. For some reason my brain keeps wanting to move the opposite of how it works. An option to reverse it would be nice.
Thanks!

**Comment by 89pleasure** [comment]
I'm going to add this feature by today. :)

**Comment by hufftheweevil** [comment]
Awesome!
What do you think about an option to switch the functions of Ctrl and Alt?
I find myself needing to use the elevation change more often than the mode change, and my personal preference would be for the elevation change to use Ctrl. I also keeping thinking to myself, Alt for alternate mode, Ctrl for controlling the elevation. But then I keep using the wrong key. Maybe it's just me...
I hate to complicate UIs, but curious if you think this is something others might want to?

**Comment by 89pleasure** [comment]
Reverse wheels are also now in version v0.4.0. 
Regarding swapping the hotkeys, that's already prepared actually, and the mod is capable of doing that already, but need to add it to the ui. Might come starting next week or by sunday, dunno yet.
