### ISSUE TITLE
Bug: Alt+RightClick resets road

### ISSUE THREAD

**Issue by hufftheweevil** [89pleasure/cities2-extended-hotkeys#4]
Often times I find myself needing to adjust the elevation step size after I've already started building a road (in the curve/complex curve/continuous modes). If you've already placed at least the first part of such curve, then using Alt+RightClick to adjust the elevation step causes the temporary road to be reset.
Is there a way to prevent this from happening?

**Comment by 89pleasure** [comment]
Yeah I'm aware of this issue. I already dislike it. I would have to disable the right click action as long the shortcut is pressed.
Problem is, you can't disable/enable an action just so. So I have to look into it a bit more to get this done.

**Comment by hufftheweevil** [comment]
Yeah I had a feeling it was going to be tricky. I suppose an alterative would be to not use the right click and instead use a key combo.

**Comment by 89pleasure** [comment]
It's already in the newest version ;)
