### ISSUE TITLE
[Enhancement] - Hotkeys for opening / selecting road tools menu, zoning menu and so on

### ISSUE THREAD

**Issue by Fenrir200678** [89pleasure/cities2-extended-hotkeys#5]
Hi,

first of all thank for developing this mod. One of the biggest things that annoy me in CS:2 are the lack of hotkeys compared to CS:1. 

Would it be possible to add hotkeys for opening the different tool menus like roads, zoning, etc? Would be a lifesaver for me, since I'm still always pressing those memorized hotkeys from CS:1 due to muscle memory. :-D 

Regards,
Fen

**Comment by 89pleasure** [comment]
That would be doable. I

**Comment by Fenrir200678** [comment]
Thank you! :)

**Comment by 89pleasure** [comment]
Das tue ich! :) But of course the communication here is international so everyone can follow :)

**Comment by Fenrir200678** [comment]
Will be added in the next release. :)
