### ISSUE TITLE
Not Working Anarchy(ALT+A) new version(0.5.0)

### ISSUE THREAD

**Issue by macros98** [89pleasure/cities2-extended-hotkeys#9]
Thank you for making a useful mod and for the updates.
However, Anarchy mode does not work in this new version. This was a necessary feature, so please check it.

**Comment by 89pleasure** [comment]
It was removed due replacement mod. Please read the version updates. Use Anarchy Mod instead.

**Comment by fleps** [comment]
> It was removed due replacement mod. Please read the version updates. Use Anarchy Mod instead.

I just want to point out that nowhere you mention that the Anarchy mode was removed.
The 0.5.0 changelog here and on Thunderstore is even formatted oddly with the changes for 0.4.0 on the same line.

**Comment by 89pleasure** [comment]
That's very true. I guess I fucked up the readme. But now you know 😄 have a great holiday
